from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
AUDIO_FILES_PATH = BASE_DIR / "audio"
MICROPHONE_AUDIO_FILES_PATH = AUDIO_FILES_PATH / "microphone"
MICROPHONE_USER_AUDIO_FILES_PATH = MICROPHONE_AUDIO_FILES_PATH / "user"
MICROPHONE_ASSISTANT_AUDIO_FILES_PATH = MICROPHONE_AUDIO_FILES_PATH / "assistant"
GOOGLE_JSON_CREDENTIALS = BASE_DIR / "google_credentials.json"
